import Head from 'next/head';
import Header from '../components/Header/Header';
import Hero from '../components/Hero/Hero';
import Poster from '../components/Poster/Poster';
import Release from '../components/Release/Release';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wines</title>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Playfair+Display:wght@400;500;600&display=swap" rel="stylesheet"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Hero />
        <Release/>
        <Poster />
      </main>
    </div>
  );
}
