import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wines</title>
        <link href="https://fonts.googleapis.com/css2?family=Croissant+One&family=Poppins:wght@200;400;500;600&display=swap" rel="stylesheet"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      
    </div>
  )
}
