import { useState } from 'react';
import Head from 'next/head';
import { useTranslations } from 'next-intl';
import { sanityClient } from '../lib/sanity';
import ReactPaginate from 'react-paginate';

import { spacing } from '../config/theme';

const categoriesQuery = `*[_type == "categories" && categName == "Red wines"] {
  items
}`;

import Hero from '../components/Hero';
import Wines from '../components/Wines/Wines';
import Search from '../components/Search';

const PER_PAGE = 8;

const Shop = ({ redWines }) => {
  const t = useTranslations('HeroPages');

  const [filteredWines, setFilteredWines] = useState(redWines);
  const [currentPage, setCurrentPage] = useState(0);

  const handlePageClick = ({ selected: selectedPage }) => {
    setCurrentPage(selectedPage);
  };

  const offset = currentPage * PER_PAGE;

  const currentPageData = filteredWines.slice(offset, offset + PER_PAGE);

  const pageCount = Math.ceil(filteredWines.length / PER_PAGE);

  return (
    <>
      <div>
        <Head>
          <title>Wines</title>
          <link
            href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Playfair+Display:wght@400;500;600&display=swap"
            rel="stylesheet"
          />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Hero title={t('redWines')} />

        <Search data={filteredWines} setData={setFilteredWines} />

        {filteredWines.length === 0 ? (
          <div className="notFound">
            <h2>No wines are found!</h2>
          </div>
        ) : (
          <>
            <Wines wines={currentPageData} />
            <ReactPaginate
              previousLabel={'prev'}
              nextLabel={'next'}
              pageCount={pageCount}
              onPageChange={handlePageClick}
              containerClassName={'pagination'}
              previousLinkClassName={'pagination-link'}
              nextLinkClassName={'pagination-link'}
              disabledClassName={'pagination-link__disabled'}
              activeClassName={'pagination-link__active'}
            />
          </>
        )}
      </div>
      <style jsx>{`
        .notFound {
          margin-bottom: ${spacing.large};
          display: flex;
          justify-content: center;
        }
      `}</style>
    </>
  );
};

export default Shop;

export async function getStaticProps({ locale }) {
  const categories = await sanityClient.fetch(categoriesQuery);
  const redWines = categories?.[0]?.items.map((wine) => {
    return {
      id: wine?._key,
      title: wine?.title,
      description: wine?.description,
      price: wine?.price,
      image: wine?.image,
    };
  });
  return {
    props: {
      messages: require(`../locales/${locale}.json`),
      redWines,
    },
  };
}
