import Head from 'next/head';
import { useTranslations } from 'next-intl';

import Header from '../components/Header/Header';

const Shop = () => {
  const t = useTranslations('Shop');
  return (
    <div>
      <Head>
        <title>Wines</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Playfair+Display:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div>{t('greeting')}</div>
    </div>
  );
};

export default Shop;

export function getStaticProps({ locale }) {
  return {
    props: {
      messages: require(`../locales/${locale}.json`),
    },
  };
}
