import { useState } from 'react';
import Head from 'next/head';
import { useTranslations } from 'next-intl';
import { sanityClient } from '../lib/sanity';

import { spacing } from '../config/theme';

const categoriesQuery = `*[_type == "categories" && categName == "White wines"] {
  items
}`;

import Hero from '../components/Hero';
import Wines from '../components/Wines/Wines';
import Search from '../components/Search';

const Shop = ({ whiteWines }) => {
  const t = useTranslations('HeroPages');

  const [filteredWines, setFilteredWines] = useState(whiteWines);

  return (
    <>
      <div>
        <Head>
          <title>Wines</title>
          <link
            href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Playfair+Display:wght@400;500;600&display=swap"
            rel="stylesheet"
          />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Hero title={t('whiteWines')} />

        <Search data={filteredWines} setData={setFilteredWines} />

        {filteredWines.length === 0 ? (
          <div className="notFound">
            <h2>No wines are found!</h2>
          </div>
        ) : (
          <Wines wines={filteredWines} />
        )}
      </div>
      <style jsx>{`
        .notFound {
          margin-bottom: ${spacing.large};
          display: flex;
          justify-content: center;
        }
      `}</style>
    </>
  );
};

export default Shop;

export async function getStaticProps({ locale }) {
  const categories = await sanityClient.fetch(categoriesQuery);
  const whiteWines = categories?.[0]?.items.map((wine) => {
    return {
      id: wine?._key,
      title: wine?.title,
      description: wine?.description,
      price: wine?.price,
      image: wine?.image,
    };
  });
  return {
    props: {
      messages: require(`../locales/${locale}.json`),
      whiteWines,
    },
  };
}
